image: node:18.13.0-alpine

stages:
  - test
  - build
  - deploy

default:
  cache:
    key: "$CI_BUILD_NAME"
    paths:
      - node_modules
  before_script:
    - npm install

unit_test:
  stage: test
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    expire_in: "1 week"
    paths:
      - coverage/lcov.info
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/clover.xml
      junit:
        - junit.xml
  script:
    - echo "Running unit tests"
    - npm run test:coverage
  only:
    refs:
      - merge_requests
      - main

e2e_test:
  stage: test
  dependencies:
    - unit_test
  script:
    - echo "Running e2e tests"
  only:
    refs:
      - merge_requests
      - main

test_build:
  stage: test
  dependencies:
    - unit_test
  script:
    - npm run build
  only:
    refs:
      - merge_requests

build:
  stage: build
  dependencies:
    - unit_test
    - e2e_test
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - build/
    when: on_success
    expire_in: "24 hours"
  script:
    - npm run build
  only:
    refs:
      - main

deploy_docker_image:
  stage: deploy
  dependencies:
    - build
  script:
    - sh ./build.sh
    - echo "Need to setup docker registry and deploy"
  only:
    refs:
      - main
