version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker123/orion/docker/mysql
      - MYSQL_DATABASE=orion
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    container_name: app
    restart: always
    build:
      context: .
      target: production
    ports:
      - "5555:5555"
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker123
      - MYSQL_DB_NAME=orion
    command: dumb-init node server.js

volumes:
  mysql_data:
