version: '3.8'

networks:
  proxy:
    driver: bridge

services:
  next_lotus_ao_redis:
    container_name: "next_lotus_ao_redis"
    image: redis
    networks:
      - proxy
    ports:
      - "${BULL_REDIS_PORT}:6379"

  next_lotus_ao_mysql:
    container_name: next_lotus_ao_mysql
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - proxy
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - next_lotus_ao_mysql_data:/var/lib/mysql

  next_lotus_ao_app:
    container_name: next_lotus_ao_app
    restart: always
    build:
      context: .
      target: production
    ports:
      - "5555:5555"
      - "8080:8080"
    networks:
      - proxy
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
    command: dumb-init node server.js
    depends_on:
      - next_lotus_ao_redis
      - next_lotus_ao_mysql

volumes:
  next_lotus_ao_mysql_data:
