version: '3.8'

services:
  next_lotus_ao_redis:
    container_name: "next_lotus_ao_redis"
    image: redis
    ports:
      - "6379:6379"

  next_lotus_ao_mysql:
    container_name: next_lotus_ao_mysql
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - next_lotus_ao_mysql_data:/var/lib/mysql

volumes:
  next_lotus_ao_mysql_data:
